routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'ContactController@index')->name('contacts.index');

Route::get('/add', 'ContactController@create')->name('contacts.create');
Route::post('/add', 'ContactController@post');

Route::get('/contact/{contact}', 'ContactController@update')->name('contacts.update');
Route::delete('/contact/{contact}', 'ContactController@delete')->name('contacts.delete');
Route::put('/contact/{contact}', 'ContactController@put');

app/Contact.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Str;

class Contact extends Model
{
    use SoftDeletes;

    protected $appends = ['fullname'];


    public static function boot()
    {
		parent::boot();
    
        self::creating(function ($model) {
            $model->uuid = (string) Str::uuid();
        });

    }

    /**
     * Decrypt the user's email.
     *
     * @return string
     */
    public function getEmailAttribute($value)
    {
        return decrypt($value);
    }

    /**
     * Decrypt the user's phone.
     *
     * @return string
     */
    public function getPhoneAttribute($value)
    {
        return decrypt($value);
    }

    /**
     * Decrypt the user's first name.
     *
     * @return string
     */
    public function getFirstnameAttribute($value)
    {
        return decrypt($value);
    }

    /**
     * Decrypt the user's last name.
     *
     * @return string
     */
    public function getLastnameAttribute($value)
    {
        return decrypt($value);
    }
     /**
     * Get the user's full name.
     *
     * @return string
     */
    public function getFullnameAttribute()
    {
        return $this->firstname." ".$this->lastname;
    }

    
	public function getRouteKeyName(){
    	return 'uuid';
    }

	public function getEditUrlAttribute(){
		return route('contacts.update', $this);
	}

	public function getDeleteUrlAttribute(){
		return route('contacts.delete', $this);
	}
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/ContactController.php
<?php

namespace App\Http\Controllers;

use App\Contact;
use Illuminate\Http\Request;
use App\Http\Requests\UpdateContact;

class ContactController extends Controller
{

    public function index(){

        $contact = new Contact; 
        return view('contacts.index',['contacts' => $contact->get()->all()]);
    }
    
    public function create(Contact $contact){

        return view('contacts.create');
    }
    
    public function post(UpdateContact $request){

        $validated = $request->validated();
        
        $contact = New Contact;
        $contact->firstname = encrypt($validated['firstname']);
        $contact->lastname = encrypt($validated['lastname']);
        $contact->email = encrypt($validated['email']);
        $contact->phone = encrypt($validated['phone']);
        
        //save resource
        $contact->save();
     
        return redirect()->route('contacts.index')->with('alert', trans('app.saved'));
    }


    public function update(Contact $contact){

        return view('contacts.update',['contact' => $contact]);
    }
    
    public function put(Contact $contact, UpdateContact $request){

        $validated = $request->validated();
        
        //update contact resource with validated data
        $contact->firstname = encrypt($validated['firstname']);
        $contact->lastname = encrypt($validated['lastname']);
        $contact->email = encrypt($validated['email']);
        $contact->phone = encrypt($validated['phone']);
        
        //save resource
        $contact->save();
     
        return redirect()->route('contacts.index')->with('alert', trans('app.saved'));
    }
    
    public function delete(Contact $contact){
        
        $contact->delete();
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

resources/views/contacts/create.blade.php
@extends('template')

@section('title', 'Add new contact')

@section('content')


    <form method="post" action="{{route('contacts.create')}}">
        @csrf

        @if ($errors->any())
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif 
    
        <div class="row">
            <div class="col-6">
                <div class="form-group">
                    <label for="firstname">{{__('app.firstname')}}</label>
                    <input type="text" name="firstname" class="form-control" id="firstname" value="{{ Request::old('firstname') }}">
                </div>
            </div>
            <div class="col-6">
                <div class="form-group">
                    <label for="lastname">{{__('app.lastname')}}</label>
                    <input type="text" name="lastname" class="form-control" id="lastname" value="{{ Request::old('lastname') }}">
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-6">
                <div class="form-group">
                    <label for="email">{{__('app.email')}}</label>
                    <input type="email" name="email" class="form-control" id="email" value="{{ Request::old('email') }}">
                </div>
            </div>
            <div class="col-6">
                <div class="form-group">
                    <label for="phone">{{__('app.phone')}}</label>
                    <input type="phone" name="phone" class="form-control" id="phone" value="{{ Request::old('phone') }}">
                </div>
            </div>
        </div>

        <button type="submit" class="btn btn-primary">{{__('app.submit')}}</button>
    
    </form>

@endsection

resources/views/contacts/index.blade.php
@extends('template')

@section('title', 'Contacts overview')

@section('content')
    
    @if (session('alert'))
        <div class="alert alert-success m-0 _success mb-3">
            {{ session('alert') }}
        </div>
    @endif

    <div class="row">
    
        @foreach ($contacts as $contact)
            <div class="col-6 col-md-4 pb-4">
                @include('components/contact-card')
            </div>
        @endforeach
    </div>

   @include('components/delete-modal')

@endsection

resources/views/contacts/update.blade.php
@extends('template')

@section('title', 'Edit contact - ' . $contact->fullname)

@section('content')


    <form method="post" action="{{$contact->edit_url}}">
        @csrf
        <input name="_method" type="hidden" value="put">

        @if ($errors->any())
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif 
    

        <div class="row">
            <div class="col-6">
                <div class="form-group">
                    <label for="firstname">{{__('app.firstname')}}</label>
                    <input type="text" name="firstname" class="form-control" id="firstname" value="{{Request::old('firstname') ?? $contact->firstname}}">
                </div>
            </div>
            <div class="col-6">
                <div class="form-group">
                    <label for="lastname">{{__('app.lastname')}}</label>
                    <input type="text" name="lastname" class="form-control" id="lastname" value="{{Request::old('lastname') ?? $contact->lastname}}">
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-6">
                <div class="form-group">
                    <label for="email">{{__('app.email')}}</label>
                    <input type="email" name="email" class="form-control" id="email" value="{{Request::old('email') ?? $contact->email}}">
                </div>
            </div>
            <div class="col-6">
                <div class="form-group">
                    <label for="phone">{{__('app.phone')}}</label>
                    <input type="tel" name="phone" class="form-control" id="phone" value="{{Request::old('phone') ?? $contact->phone}}">
                </div>
            </div>
        </div>

        <button type="submit" class="btn btn-primary">{{__('app.submit')}}</button>
    
    </form>


@endsection

resources/views/template.blade.php
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="csrf-token" content="{{ csrf_token() }}">

        <title>@yield('title','Ef2 contacts')</title>

        <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" rel="stylesheet">    
    </head>
    <body>
        

        <div class="container py-4">

            <div class="row">
                <div class="col-12 col-sm-6 col-md-3">
                    <div class="list-group">
                        <div class="list-group-item">
                            <h3>{{__('app.contacts')}}</h3>
                        </div>
                        <a href="{{route('contacts.index')}}" class="list-group-item list-group-item-action">{{__('app.overview')}}</a>
                        <a href="{{route('contacts.create')}}" class="list-group-item list-group-item-action ">{{__('app.add')}}</a>
                    </div>
                </div>

                <div class="col-12 col-sm-6 col-md-9">
                    @yield('content')
                </div>
            </div>

        </div>
        <script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
        <script type="text/javascript" src="{{ asset('js/app.js') }}"></script>
    </body>
</html>